services:
  postgres:
    image: postgres:16-alpine
    container_name: cash-money-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cash_money
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: mount init scripts
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
# Notes for NAS migration:
# - When moving to NAS, update the DATABASE_URL in .env to point to your NAS IP
# - You can use the same docker-compose.yml on your NAS
# - Consider setting up proper backup strategies on the NAS
# - For production, update POSTGRES_PASSWORD to a secure value
